#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat
FROM dockerrepoapi.tamro.lt/dotnet/sdk:8.0.200-bookworm-slim AS build
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY . ./
RUN dotnet restore Tamro.Madam.RestApi/Tamro.Madam.RestApi.csproj
# Copy everything else and build
RUN dotnet publish Tamro.Madam.RestApi/Tamro.Madam.RestApi.csproj -c Release

# Build runtime image
FROM dockerrepoapi.tamro.lt/dotnet/aspnet:8.0.200-bookworm-slim AS runtime
WORKDIR /app
COPY --from=build /app/Tamro.Madam.RestApi/bin/Release/net8.0/publish .

ENV ASPNETCORE_URLS=http://+:7000
ARG APP_ENV
ENV ASPNETCORE_ENVIRONMENT ${APP_ENV}


EXPOSE 7000/tcp
#ENTRYPOINT ["sleep","3600"] for testing purposes
ENTRYPOINT ["dotnet", "Tamro.Madam.RestApi.dll"]
