// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tamro.Madam.Repository.Context.Madam;

#nullable disable

namespace Tamro.Madam.Repository.Migrations
{
    [DbContext(typeof(MadamDbContext))]
    [Migration("20241121084748_AddBalticCountry")]
    partial class AddBalticCountry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Atcs.Atc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ATC");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Barcodes.Barcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ean")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EAN");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Measure")
                        .HasColumnType("int")
                        .HasColumnName("Measure");

                    b.Property<DateTime?>("RowVer")
                        .HasColumnType("datetime")
                        .HasColumnName("EditedAt");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Barcode", null, t =>
                        {
                            t.HasTrigger("TR_Barcode_EditedAt");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Brands.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Customers.CustomerLegalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("E1SoldTo")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("RowVer")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("CustomerLegalEntity", (string)null);
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Customers.CustomerLegalEntityNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CustomerLegalEntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowVer")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("SendCanceledOrderNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("CustomerLegalEntityId")
                        .IsUnique();

                    b.ToTable("CustomerLegalEntityNotification", (string)null);
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Customers.E1.Customer", b =>
                {
                    b.Property<int>("AddressNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressNumber"));

                    b.Property<string>("AdditionalTaxId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailingName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("AddressNumber");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Forms.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Form");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.Bindings.ItemBinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("LocalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemBinding", null, t =>
                        {
                            t.HasTrigger("TR_ItemBinding_Delete");

                            t.HasTrigger("TR_ItemBinding_InsertUpdate");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.Bindings.ItemBindingLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemBindingId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemBindingId");

                    b.ToTable("ItemLanguages");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.Bindings.Retail.GeneratedRetailCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<string>("CodePrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Country", "CodePrefix", "Code")
                        .IsUnique();

                    b.ToTable("GeneratedRetailCodes");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.Bindings.Vlk.VlkBinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemBindingId")
                        .HasColumnType("int");

                    b.Property<int>("NpakId7")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemBindingId");

                    b.HasIndex("NpakId7")
                        .IsUnique();

                    b.ToTable("VlkBinding");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int")
                        .HasColumnName("Active");

                    b.Property<string>("ActiveSubstance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AtcId")
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ItemName");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Regular");

                    b.Property<decimal?>("Measure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MeasurementUnitId")
                        .HasColumnType("int")
                        .HasColumnName("UOMId");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int?>("ParallelParentItemId")
                        .HasColumnType("int");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestorId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Strength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupplierNickId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtcId");

                    b.HasIndex("BrandId");

                    b.HasIndex("FormId");

                    b.HasIndex("MeasurementUnitId");

                    b.HasIndex("ProducerId");

                    b.HasIndex("RequestorId");

                    b.HasIndex("SupplierNickId");

                    b.ToTable("Item", null, t =>
                        {
                            t.HasTrigger("TR_Item_Delete");

                            t.HasTrigger("TR_Item_InsertUpdate");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.ItemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("ActiveSubstance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AtcId")
                        .HasColumnType("int")
                        .HasColumnName("AtcId");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("Deleted")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Dose")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Measure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int?>("ParallelParentItemId")
                        .HasColumnType("int");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestorId")
                        .HasColumnType("int");

                    b.Property<string>("Strength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupplierNickId")
                        .HasColumnType("int");

                    b.Property<int?>("UomId")
                        .HasColumnType("int")
                        .HasColumnName("UOMId");

                    b.HasKey("Id");

                    b.ToTable("ItemLog");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.SafetyStocks.SafetyStock", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("SafetyStockItemId");

                    b.Property<decimal?>("RetailQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("WholesaleQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SafetyStock");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.SafetyStocks.SafetyStockCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanBuy")
                        .HasColumnType("bit");

                    b.Property<int>("CheckDays")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("RestrictionLevel")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("RowVer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("SafetyStockItemId")
                        .HasColumnType("int");

                    b.Property<string>("SafetyStockPharmacyChainGroup")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("SafetyStockPharmacyChainId")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SafetyStockPharmacyChainId");

                    b.HasIndex("SafetyStockItemId", "SafetyStockPharmacyChainGroup")
                        .IsUnique()
                        .HasFilter("(SafetyStockPharmacyChainId IS NULL)");

                    b.HasIndex("SafetyStockItemId", "SafetyStockPharmacyChainId", "SafetyStockPharmacyChainGroup")
                        .IsUnique()
                        .HasFilter("(SafetyStockPharmacyChainId IS NOT NULL)");

                    b.ToTable("SafetyStockCondition");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.SafetyStocks.SafetyStockGridData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CanBuy")
                        .HasColumnType("bit");

                    b.Property<int>("CheckDays")
                        .HasColumnType("int");

                    b.Property<string>("Cn1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cn3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ItemGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PharmacyChainDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PharmacyChainId")
                        .HasColumnType("int");

                    b.Property<string>("ProductClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuantityToBuy")
                        .HasColumnType("int");

                    b.Property<decimal?>("RetailQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SafetyStockPharmacyChainGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Substance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierNick")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupplierNumber")
                        .HasColumnType("int");

                    b.Property<int?>("WholesaleQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("v_SafetyStockGrid");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.SafetyStocks.SafetyStockItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Cn1")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Cn3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ItemGroup")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("ItemName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ItemNo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ProductClass")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Substance")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SupplierNick")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("SupplierNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemNo", "Country")
                        .IsUnique();

                    b.ToTable("SafetyStockItem");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.SafetyStocks.SafetyStockPharmacyChain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("E1SoldTo")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Country", "E1SoldTo")
                        .IsUnique();

                    b.ToTable("SafetyStockPharmacyChain");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.MeasurementUnits.MeasurementUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UOM");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Nicks.Nick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SupplierNick");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Producers.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Producer");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Requestors.Requestor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Requestor");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Sales.CanceledOrderLines.E1CanceledOrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerOrderNo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("E1ShipTo")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("RowVer")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("E1CanceledOrderHeader");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Sales.CanceledOrderLines.E1CanceledOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanceledQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("E1CanceledOrderHeaderId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmailStatus")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ItemNo2")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("LastStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NotificationSendDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderLineNo")
                        .HasColumnType("int");

                    b.Property<int>("OrderedQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowVer")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("E1CanceledOrderHeaderId");

                    b.ToTable("E1CanceledOrderLine");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Sales.Sabis.SksContractMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalTaxId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("AddressNumber")
                        .HasColumnType("int");

                    b.Property<string>("ContractSabis")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ContractSabis");

                    b.Property<string>("ContractTamro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EditedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RowVer")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AddressNumber")
                        .IsUnique();

                    b.ToTable("SKS_Contract_mapping", (string)null);
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Users.UserSettings.UserSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int?>("RowsPerPage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Wholesale.Lv.LvWholesaleCustomer", b =>
                {
                    b.Property<int>("AddressNumber")
                        .HasColumnType("int");

                    b.Property<int>("AddressNumber2")
                        .HasColumnType("int");

                    b.Property<string>("MailingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("LvWholesaleCustomer");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Wholesale.Lv.LvWholesaleItem", b =>
                {
                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ItemDescription1");

                    b.Property<string>("ItemNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ItemNo2");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("TamroUtilities.EFCore.Models.DbAuditEntry", b =>
                {
                    b.Property<int>("AuditEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditEntryID"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntitySetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditEntryID");

                    b.ToTable("AuditEntry");
                });

            modelBuilder.Entity("TamroUtilities.EFCore.Models.DbAuditEntryProperty", b =>
                {
                    b.Property<int>("AuditEntryPropertyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditEntryPropertyID"));

                    b.Property<int>("AuditEntryID")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditEntryPropertyID");

                    b.HasIndex("AuditEntryID");

                    b.ToTable("AuditEntryProperty");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Barcodes.Barcode", b =>
                {
                    b.HasOne("Tamro.Madam.Repository.Entities.Items.Item", "Item")
                        .WithMany("Barcodes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Barcode_Item");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Customers.CustomerLegalEntityNotification", b =>
                {
                    b.HasOne("Tamro.Madam.Repository.Entities.Customers.CustomerLegalEntity", null)
                        .WithOne("NotificationSettings")
                        .HasForeignKey("Tamro.Madam.Repository.Entities.Customers.CustomerLegalEntityNotification", "CustomerLegalEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.Bindings.ItemBinding", b =>
                {
                    b.HasOne("Tamro.Madam.Repository.Entities.Items.Item", "Item")
                        .WithMany("Bindings")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.Bindings.ItemBindingLanguage", b =>
                {
                    b.HasOne("Tamro.Madam.Repository.Entities.Items.Bindings.ItemBinding", "ItemBinding")
                        .WithMany("Languages")
                        .HasForeignKey("ItemBindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemBinding");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.Bindings.Vlk.VlkBinding", b =>
                {
                    b.HasOne("Tamro.Madam.Repository.Entities.Items.Bindings.ItemBinding", "ItemBinding")
                        .WithMany()
                        .HasForeignKey("ItemBindingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemBinding");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.Item", b =>
                {
                    b.HasOne("Tamro.Madam.Repository.Entities.Atcs.Atc", "Atc")
                        .WithMany("Items")
                        .HasForeignKey("AtcId")
                        .HasConstraintName("FK_Item_BATC");

                    b.HasOne("Tamro.Madam.Repository.Entities.Brands.Brand", "Brand")
                        .WithMany("Items")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Item_Brand");

                    b.HasOne("Tamro.Madam.Repository.Entities.Forms.Form", "Form")
                        .WithMany("Items")
                        .HasForeignKey("FormId")
                        .HasConstraintName("FK_Item_Form");

                    b.HasOne("Tamro.Madam.Repository.Entities.MeasurementUnits.MeasurementUnit", "MeasurementUnit")
                        .WithMany("Items")
                        .HasForeignKey("MeasurementUnitId");

                    b.HasOne("Tamro.Madam.Repository.Entities.Producers.Producer", "Producer")
                        .WithMany("Items")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Item_Producer");

                    b.HasOne("Tamro.Madam.Repository.Entities.Requestors.Requestor", "Requestor")
                        .WithMany("Items")
                        .HasForeignKey("RequestorId")
                        .HasConstraintName("Item_RequestorIdr_FK");

                    b.HasOne("Tamro.Madam.Repository.Entities.Nicks.Nick", "SupplierNick")
                        .WithMany("Items")
                        .HasForeignKey("SupplierNickId");

                    b.Navigation("Atc");

                    b.Navigation("Brand");

                    b.Navigation("Form");

                    b.Navigation("MeasurementUnit");

                    b.Navigation("Producer");

                    b.Navigation("Requestor");

                    b.Navigation("SupplierNick");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.SafetyStocks.SafetyStock", b =>
                {
                    b.HasOne("Tamro.Madam.Repository.Entities.Items.SafetyStocks.SafetyStockItem", null)
                        .WithOne("SafetyStock")
                        .HasForeignKey("Tamro.Madam.Repository.Entities.Items.SafetyStocks.SafetyStock", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.SafetyStocks.SafetyStockCondition", b =>
                {
                    b.HasOne("Tamro.Madam.Repository.Entities.Items.SafetyStocks.SafetyStockItem", "SafetyStockItem")
                        .WithMany("SafetyStockConditions")
                        .HasForeignKey("SafetyStockItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tamro.Madam.Repository.Entities.Items.SafetyStocks.SafetyStockPharmacyChain", "SafetyStockPharmacyChain")
                        .WithMany()
                        .HasForeignKey("SafetyStockPharmacyChainId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SafetyStockItem");

                    b.Navigation("SafetyStockPharmacyChain");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Sales.CanceledOrderLines.E1CanceledOrderLine", b =>
                {
                    b.HasOne("Tamro.Madam.Repository.Entities.Sales.CanceledOrderLines.E1CanceledOrderHeader", null)
                        .WithMany("Lines")
                        .HasForeignKey("E1CanceledOrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Sales.Sabis.SksContractMapping", b =>
                {
                    b.HasOne("Tamro.Madam.Repository.Entities.Customers.E1.Customer", "Customer")
                        .WithOne()
                        .HasForeignKey("Tamro.Madam.Repository.Entities.Sales.Sabis.SksContractMapping", "AddressNumber");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TamroUtilities.EFCore.Models.DbAuditEntryProperty", b =>
                {
                    b.HasOne("TamroUtilities.EFCore.Models.DbAuditEntry", "AuditEntry")
                        .WithMany("Properties")
                        .HasForeignKey("AuditEntryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditEntry");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Atcs.Atc", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Brands.Brand", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Customers.CustomerLegalEntity", b =>
                {
                    b.Navigation("NotificationSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Forms.Form", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.Bindings.ItemBinding", b =>
                {
                    b.Navigation("Languages");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.Item", b =>
                {
                    b.Navigation("Barcodes");

                    b.Navigation("Bindings");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Items.SafetyStocks.SafetyStockItem", b =>
                {
                    b.Navigation("SafetyStock")
                        .IsRequired();

                    b.Navigation("SafetyStockConditions");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.MeasurementUnits.MeasurementUnit", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Nicks.Nick", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Producers.Producer", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Requestors.Requestor", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tamro.Madam.Repository.Entities.Sales.CanceledOrderLines.E1CanceledOrderHeader", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("TamroUtilities.EFCore.Models.DbAuditEntry", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
