using System.ComponentModel;
using Tamro.Madam.Models.General;

namespace Tamro.Madam.Models.ItemMasterdata.Items.Bindings.Retail;

public class GeneratedRetailCodeModel
{
    public int Id { get; set; }
    public BalticCountry Country { get; set; }
    [DisplayName("Code prefix")]
    public string CodePrefix { get; set; }
    public long Code { get; set; }
    [DisplayName("Full code")]
    public string FullCode
    {
        get
        {
            return CodePrefix + Code;
        }
    }
    [DisplayName("Generated by")]
    public string GeneratedBy { get; set; }
}
